name: build android shared libs for ffmpeg

on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build-android-libs:
    name: Android for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Display NDK HOME, SDK HOME etc.
        shell: bash
        run: |
          echo "ANDROID_SDK_HOME=${ANDROID_SDK_ROOT}" >> "$GITHUB_ENV"
          echo "ANDROID_NDK_HOME: ${ANDROID_NDK_HOME}"
          echo "ANDROID_SDK_ROOT: ${ANDROID_SDK_ROOT}"
          echo "JAVA_HOME: ${JAVA_HOME}"

      - name: Build ffmpeg with scripts
        shell: bash
        run: |
          git submodule update --init --recursive

          pushd ffmpeg-android-maker

          FFMPEG_VERSION_NUMBER=$(grep "FFmpeg" ../ffmpeg_version.txt  | cut -d " " -f 2)
          echo "FFMPEG_VERSION_NUMBER: ${FFMPEG_VERSION_NUMBER}"
          sed -i "s/7.0/${FFMPEG_VERSION_NUMBER}/" ./scripts/parse-arguments.sh
          head ./scripts/parse-arguments.sh -n20

          chmod +x ffmpeg-android-maker.sh
          ./ffmpeg-android-maker.sh

          popd

      - name: Copy files
        id: copy_files
        shell: bash
        run: |
          FFMPEG_VERSION=v$(grep "FFmpeg" ./ffmpeg_version.txt  | cut -d " " -f 2)
          echo "FFMPEG_VERSION=$FFMPEG_VERSION" >> "$GITHUB_ENV"

          filename=ffmpeg_android_shared_libs-${FFMPEG_VERSION}.tar.bz2
          tar cjvf $filename ./ffmpeg-android-maker/output

      - name: Commit built libs to separate branch
        run: |
          PUSH_DIR=push_dir
          mkdir -p ${PUSH_DIR}

          pushd ${PUSH_DIR}
          cp -r ../ffmpeg-android-maker/output .
          cp ../ffmpeg_version.txt .
          popd

      - name: Push to separate branch, i.e build branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build_v6.1.2
          FOLDER: push_dir
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}"

      - name: Release android libs
        uses: svenstaro/upload-release-action@v2
        with:
          file: ffmpeg*.tar.bz2
          file_glob: true
          overwrite: true
          